### ISSUE TITLE
Sleep not working correctly after Catalina update

### ISSUE THREAD

**Issue by abala16** [AMD-OSX/bugtracker#12] opened 2019-10-10 17:25 UTC
Update to Catalina from Mojave completed with no problems. After update, however, sleep no longer functions. The OS goes to sleep and the monitor and keyboard/mouse lights turn off, but the actual system doesn't go to sleep. Power stays on and fans spin up faster. At this point the computer is in a stuck state and can't be woken back up. Only way to get back into the OS is a hard reset. The fans spinning up is something that usually happens for about a second before the computer goes to sleep on Windows 10 and Mojave, but on Catalina it just stays in that state.

Cpu: R5 1600
Mobo: MSI B350 Tomahawk
GPU: MSI Air Boost OC RX Vega 56
Kexts: Lilu, WhateverGreen (both updated)

**Comment by togbyte** [comment] 2020-07-16 17:29
I have a same problem originally reported by abala16 -  sleep no longer functions. The OS goes to sleep and the monitor and keyboard/mouse lights turn off, but the actual system doesn't go to sleep. Power stays on and fans spin up faster. At this point the computer is in a stuck state and can't be woken back up. Only way to get back into the OS is a hard reset. 

I had 10.15.5 fresh install. I just upgraded to 10.15.6 but same issue. I also have Mojave install with same Opencore and BIOS settings, and sleep works fine in Mojave. I think it's a issue between Catalina and/or OpenCore...

**Comment by rchunping** [comment] 2020-08-05 02:23
same  issue
AMD 3700X
GIGABYTE X570 I AORUS PRO WIFI

**Comment by kprinssu** [comment] 2020-08-07 20:39
It looks the solution is to remove SSDT-USBX/fix the power injection values AND to have a proper USB mapping (see https://github.com/dortania/bugtracker/issues/15).

**Comment by dhinakg** [comment] 2020-08-08 00:21
> It looks the solution is to remove SSDT-USBX/fix the power injection values AND to have a proper USB mapping (see [dortania/bugtracker#15](https://github.com/dortania/bugtracker/issues/15)).
> 
> I have not been able to get it work on my own build.

Can't reproduce. Tried combinations of mapping + removing/fixing power properties myself (also tried adding in that one extra property from the old DSDT USB fix patch), did not work.
ASRock B450 Pro4 if it matters.

**Comment by kprinssu** [comment] 2020-08-08 14:35
@dhinakg Same here (it is not working). It was something I came across and wanted to shine more line upon.

I am going to install 10.14 (Mojave) and see if that fixes anything on my end.

**Comment by togbyte** [comment] 2020-08-08 15:53
Sleep worked for me in Mojave out of the box without USB mapping. Asus X570-I motherboard. In Mojave, it was impossible for me to get the sleep to not work.

**Comment by dhinakg** [comment] 2020-08-09 22:54
While I have to unplug my USB header splitter (which seems to be bugged, as I have issues in windows and macOS) and need to press twice to wake via USB, sleep in Mojave works. I do get some errors in the log when resuming from sleep, which is interesting. 

For people where Mojave works but not Catalina, can you boot Mojave, sleep, wake, then run the following command and upload `usb_log.txt`? It’ll be found on the desktop. 

```
log show --last 10m --predicate 'process == "kernel"' | grep -i usb > ~/Desktop/usb_log.txt
```

An ioreg from IORegistryExplorer would also be appreciated.

**Comment by jubarim** [comment] 2020-08-17 17:23
> While I have to unplug my USB header splitter (which seems to be bugged, as I have issues in windows and macOS) and need to press twice to wake via USB, sleep in Mojave works. I do get some errors in the log when resuming from sleep, which is interesting.
> 
> For people where Mojave works but not Catalina, can you boot Mojave, sleep, wake, then run the following command and upload `usb_log.txt`? It’ll be found on the desktop.
> 
> ```
> log show --last 10m --predicate 'process == "kernel"' | grep -i usb > ~/Desktop/usb_log.txt
> ```
> 
> An ioreg from IORegistryExplorer would also be appreciated.

I have a Mojave install (it was using clover, but I could boot it with the same Catalina's EFI I generated yesterday using dortania tutorial with OC 0.60.0):

<script src="https://gist.github.com/jubarim/0ae17b8541f073364c0d3e681dde7210.js"></script>
https://gist.github.com/jubarim/0ae17b8541f073364c0d3e681dde7210

[ioreg.zip](https://github.com/AMD-OSX/bugtracker/files/5085789/ioreg.zip)

Mojave works fine!! It sleeps perfectly with my Dell monitor's USB 3.0 hub connected (where I have the keyboard and mouse connected). 

Catalina does not sleep with this usb hub connected, it just turns off the HDD (I can hear it turning off), but the cpu cooler and VGA does not sleep. It does not "awake" from this state, I have to force reset...

If I remove the Dell's usb hub, Catalina sleeps and awakes fine.

I have tried to remove SSDT-USBX.aml as said somewhere else (https://github.com/dortania/bugtracker/issues/15), but the issue remains.

I have not done any USB mapping in Mojave nor in Catalina - (sorry, but the usb mapping tutorial is so hard to understand, I have tried twice but I gave up...).

**Comment by jubarim** [comment] 2020-08-17 17:47
> It looks the solution is to remove SSDT-USBX/fix the power injection values AND to have a proper USB mapping (see [dortania/bugtracker#15](https://github.com/dortania/bugtracker/issues/15)).
> 
> I have not been able to get it work on my own build.

Hi!

When you say SSDT-USBX, it is the one dortania has precompiled?

In my build I have:
![ACPIs](https://user-images.githubusercontent.com/7058884/90426880-20e8cd00-e098-11ea-9d24-9f3b404c9904.png)

SSDT-EC.aml was generated using SSDTTime
SSDT-USBX.aml was downloaded precompiled [here](https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html#running-ssdttime).

I have tried removing the SSDT-USBX.aml, but the sleep issue with Catalina still happens (HDD stops spinning, but CPU and case fans keeps spinning and computer do not sleep and cannot be "awaken" from this state).

My setup:
Gigabyte B450 Aorus + Ryzen 5 3600 + Radeon RX 580.

Thanks a lot!

**Comment by rchunping** [comment] 2020-10-11 13:46
upgrade to Big Sur Beta8，Beta9

sleep/wake problem has been fixed

AMD 3700X
GIGABYTE X570 I AORUS PRO WIFI

**Comment by hetaldesai** [comment] 2020-10-11 17:14
I have MSI X570 A-Pro and when I try to shut down the machine it is rebooting....PLEAS HELP!!!

**Comment by teknologist** [comment] 2020-10-11 17:43
@rchunping confirmed here also sleep/wake works 9n bigsur beta 9 as good as it used to work on Mojave.

Thank god! At last!

Aorus x570 master / 3900X

**Comment by alyxferrari** [comment] 2022-02-15 18:34
Closing as it seems this issue has been fixed based on the previous comments.

**Closed by alyxferrari** 2022-02-15 18:34 UTC
